# Generated by Django 4.2.16 on 2026-08-17 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0048_bulkstudentcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blanks'), ('matching', 'Matching'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('comprehension', 'Comprehension'), ('problem_solving', 'Problem Solving'), ('mental_math', 'Mental Mathematics'), ('creative_writing', 'Creative Writing'), ('diagram_based', 'Diagram Based'), ('scenario', 'Scenario Question'), ('logical_reasoning', 'Logical Reasoning')], default='mcq', max_length=30)),
                ('options', models.JSONField(blank=True, help_text='List of options for MCQ/matching', null=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('marking_rubric', models.JSONField(blank=True, help_text='Rubric criteria for descriptive/creative questions', null=True)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('age_appropriate', 'Age Appropriate'), ('moderate', 'Moderate'), ('advanced', 'Advanced / Challenging')], default='age_appropriate', max_length=20)),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('skill', models.CharField(blank=True, max_length=150)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('ai_quality_notes', models.JSONField(blank=True, help_text='Language/age-suitability/ambiguity/curriculum quality-check output', null=True)),
                ('duplicate_flag', models.CharField(blank=True, help_text='Set when AI duplicate-detection finds a similar past question', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(default='A', help_text='A, B, C, D ...', max_length=5)),
                ('status', models.CharField(choices=[('ai_generated', 'AI Generated'), ('subject_teacher_review', 'Subject Teacher Review'), ('coordinator_review', 'Academic Coordinator Review'), ('approved', 'Approved'), ('locked', 'Locked / Finalized')], default='ai_generated', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('test_time', models.TimeField()),
                ('campus', models.CharField(blank=True, max_length=150)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('printed', 'Printed')], default='online', max_length=10)),
                ('parent_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_test_schedules', to='admin_panel.admission')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='admission_test_ai.generatedpaper')),
            ],
            options={
                'ordering': ['test_date', 'test_time'],
            },
        ),
        migrations.CreateModel(
            name='TestBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('curriculum', models.CharField(default='School Standard', max_length=100)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('total_time_minutes', models.PositiveIntegerField(default=0)),
                ('difficulty_easy_pct', models.PositiveSmallIntegerField(default=30)),
                ('difficulty_age_appropriate_pct', models.PositiveSmallIntegerField(default=40)),
                ('difficulty_moderate_pct', models.PositiveSmallIntegerField(default=20)),
                ('difficulty_advanced_pct', models.PositiveSmallIntegerField(default=10)),
                ('passing_percentage', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applying_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_blueprints', to='admin_panel.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('awaiting_evaluation', 'Awaiting Evaluation'), ('evaluated', 'Evaluated')], default='scheduled', max_length=25)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score_pct', models.FloatField(blank=True, null=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='admission_test_ai.testschedule')),
            ],
        ),
        migrations.CreateModel(
            name='ReadinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_scores', models.JSONField(blank=True, default=dict, help_text='{"English": 81, "Mathematics": 68, ...}')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('areas_for_support', models.JSONField(blank=True, default=list)),
                ('is_borderline', models.BooleanField(default=False)),
                ('borderline_note', models.TextField(blank=True)),
                ('ai_interview_questions', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_report', to='admission_test_ai.testattempt')),
            ],
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='admission_test_ai.testblueprint'),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='papers', to='admission_test_ai.admissionquestion'),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_papers_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlueprintSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('time_minutes', models.PositiveIntegerField(default=0)),
                ('topics', models.TextField(blank=True, help_text='Comma-separated topics/chapters to draw from')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='admission_test_ai.testblueprint')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('blueprint', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_test_weight_pct', models.PositiveSmallIntegerField(default=60)),
                ('previous_results_weight_pct', models.PositiveSmallIntegerField(default=15)),
                ('interview_weight_pct', models.PositiveSmallIntegerField(default=15)),
                ('teacher_observation_weight_pct', models.PositiveSmallIntegerField(default=10)),
                ('computed_score_pct', models.FloatField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('highly_recommended', 'Highly Recommended'), ('recommended', 'Recommended'), ('recommended_support', 'Recommended with Academic Support'), ('further_assessment', 'Further Assessment Required'), ('not_recommended', 'Not Recommended at Present')], max_length=30)),
                ('ai_notes', models.TextField(blank=True)),
                ('final_decision', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('accepted_conditions', 'Accepted with Conditions'), ('waitlisted', 'Waitlisted'), ('reassessment', 'Reassessment Required'), ('rejected', 'Rejected')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_ai_recommendations', to='admin_panel.admission')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('readiness_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission_test_ai.readinessreport')),
            ],
        ),
        migrations.AddField(
            model_name='admissionquestion',
            name='blueprint_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admission_test_ai.blueprintsubject'),
        ),
        migrations.AlterUniqueTogether(
            name='generatedpaper',
            unique_together={('blueprint', 'version_label')},
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('is_auto_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_suggested_marks', models.FloatField(blank=True, null=True)),
                ('marks_awarded', models.FloatField(blank=True, null=True)),
                ('teacher_approved', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='admission_test_ai.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission_test_ai.admissionquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
