# Generated by Django 5.2.3 on 2025-10-07 11:53

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('student_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelor', 'Bachelor'), ('Diploma', 'Diploma'), ('Matric', 'Matric'), ('Intermediate', 'Intermediate')], default='Matric', max_length=50)),
                ('experience', models.PositiveIntegerField(blank=True, help_text='Years of teaching experience', null=True)),
                ('is_merge', models.BooleanField(default=False)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty_group', multiselectfield.db.fields.MultiSelectField(choices=[('Pre-Primary', 'Pre-Primary'), ('Junior Section', 'Junior Section'), ('Senior Section', 'Senior Section'), ('Pre-o level', 'Pre-o level'), ('O level', 'O level')], max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_images/')),
                ('joining_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='admin_panel.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='quizzes/')),
                ('due_date', models.DateField()),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lecture_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='assignments/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('class_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.class')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.assignedperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'period')},
            },
        ),
    ]
