# Generated by Django 6.0.6 on 2026-07-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_department_designation_employee'),
        ('teacher_dashboard', '0002_attendance_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='admin_panel.employee'),
        ),
    ]
