# Generated by Django 4.2.16 on 2026-08-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0048_bulkstudentcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=30, unique=True)),
                ('reason_for_referral', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent — Immediate Safety Concern')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('monitoring', 'Monitoring / Follow-Up'), ('closed', 'Closed')], default='open', max_length=15)),
                ('support_goals', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('closure_summary', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_cases', to='admin_panel.employee')),
            ],
            options={
                'permissions': [('view_confidential_case', 'Can view confidential counselling case records')],
            },
        ),
        migrations.CreateModel(
            name='ExternalReferralContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('clinical_psychologist', 'Clinical Psychologist'), ('psychiatrist', 'Psychiatrist'), ('child_protection', 'Child Protection Services'), ('speech_therapist', 'Speech Therapist'), ('occupational_therapist', 'Occupational Therapist'), ('special_education', 'Special Education Professional'), ('rehabilitation', 'Rehabilitation Centre'), ('hospital_emergency', 'Hospital / Emergency Services')], max_length=25)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellbeingCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('mood_rating', models.PositiveSmallIntegerField(help_text='1 (low) – 5 (great)')),
                ('stress_rating', models.PositiveSmallIntegerField(help_text='1 (calm) – 5 (very stressed)')),
                ('feels_safe_at_school', models.BooleanField(default=True)),
                ('sleep_difficulty', models.BooleanField(default=False)),
                ('wants_to_talk_to_someone', models.BooleanField(default=False)),
                ('what_is_affecting_you', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_checkins', to='admin_panel.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_concern', models.TextField()),
                ('student_strengths', models.TextField(blank=True)),
                ('short_term_goals', models.TextField(blank=True)),
                ('long_term_goals', models.TextField(blank=True)),
                ('planned_interventions', models.TextField(blank=True)),
                ('responsible_staff', models.CharField(blank=True, max_length=200)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('progress_indicators', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_plan', to='counsellor_dashboard.counsellingcase')),
            ],
        ),
        migrations.CreateModel(
            name='SafeguardingConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_type', models.CharField(choices=[('bullying', 'Bullying'), ('harassment', 'Harassment'), ('abuse_neglect', 'Abuse or Neglect Concern'), ('self_harm', 'Self-Harm Concern'), ('violence_threat', 'Threat of Violence'), ('unsafe_home', 'Unsafe Home Situation'), ('other_safety', 'Other Immediate Safety Concern')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical — Immediate Action')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('safeguarding_officer_notified', 'Safeguarding Officer Notified'), ('action_in_progress', 'Action In Progress'), ('external_referral', 'External Referral Made'), ('closed', 'Closed')], default='reported', max_length=35)),
                ('reported_by_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('parent_contact_decision', models.CharField(blank=True, max_length=255)),
                ('external_referral_made', models.BooleanField(default=False)),
                ('external_referral_details', models.TextField(blank=True)),
                ('safety_plan', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('safeguarding_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safeguarding_concerns_handled', to='admin_panel.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safeguarding_concerns', to='admin_panel.student')),
            ],
            options={
                'permissions': [('view_safeguarding_concern', 'Can view safeguarding concerns (restricted)')],
            },
        ),
        migrations.CreateModel(
            name='CounsellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('initial_assessment', 'Initial Assessment'), ('individual', 'Individual Counselling'), ('group', 'Group Counselling'), ('parent_meeting', 'Parent Meeting'), ('teacher_consultation', 'Teacher Consultation'), ('crisis_response', 'Crisis Response'), ('follow_up', 'Follow-Up Session'), ('case_closure', 'Case Closure')], max_length=25)),
                ('session_datetime', models.DateTimeField()),
                ('notes', models.TextField()),
                ('next_steps', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Once approved/locked, notes should not be edited further.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counsellor_dashboard.counsellingcase')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_sessions_conducted', to='admin_panel.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_sessions_created', to='admin_panel.employee')),
            ],
            options={
                'ordering': ['-session_datetime'],
                'permissions': [('view_confidential_session_note', 'Can view confidential counselling session notes')],
            },
        ),
        migrations.CreateModel(
            name='CounsellingReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic Difficulty'), ('attendance', 'Attendance Concern'), ('behaviour', 'Behaviour Change'), ('bullying', 'Bullying'), ('peer_conflict', 'Peer Conflict'), ('family', 'Family Concern'), ('stress_anxiety', 'Stress or Anxiety'), ('grief_loss', 'Grief or Loss'), ('career', 'Career Guidance'), ('child_protection', 'Child Protection Concern')], max_length=20)),
                ('source', models.CharField(choices=[('self', 'Student (Self-Referral)'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Administrator'), ('nurse', 'Nurse / Medical Staff')], max_length=10)),
                ('referred_by_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(help_text='What prompted this referral?')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent — Immediate Safety Concern')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('accepted', 'Accepted — Case Opened'), ('declined', 'Declined / Redirected')], default='new', max_length=15)),
                ('is_emergency_service', models.BooleanField(default=False, help_text='This form is NOT an emergency service. Urgent/unsafe situations must go through the Safeguarding workflow immediately.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_referrals', to='admin_panel.student')),
            ],
        ),
        migrations.AddField(
            model_name='counsellingcase',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='counsellor_dashboard.counsellingreferral'),
        ),
        migrations.AddField(
            model_name='counsellingcase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_cases', to='admin_panel.student'),
        ),
        migrations.CreateModel(
            name='CounsellingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('mode', models.CharField(choices=[('in_person', 'In Person'), ('online', 'Online')], default='in_person', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='requested', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='counsellor_dashboard.counsellingcase')),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselling_appointments', to='admin_panel.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_appointments', to='admin_panel.student')),
            ],
        ),
    ]
