# Generated by Django 5.2.3 on 2025-10-07 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('student_profile', '0001_initial'),
        ('teacher_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedperiod',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='admin_panel.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='class_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='assignedperiod',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.classgroup'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.academicyear'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='assignedperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.createperiod'),
        ),
        migrations.AddField(
            model_name='diary',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='diary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='examformat',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.curriculumsource'),
        ),
        migrations.AddField(
            model_name='lessonplanrequest',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.guidebook'),
        ),
        migrations.AddField(
            model_name='lessonplanrequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='admin_panel.lessonplanrequest'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_panel.examformat'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='admin_panel.permission'),
        ),
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.academicyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='diary',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='assignedperiod',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='admission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.academicyear'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.stream'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='examformat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='diary',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='assignedperiod',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='subjectperiod',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.classgroup'),
        ),
        migrations.AddField(
            model_name='subjectperiod',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
        migrations.AddField(
            model_name='topic',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='admin_panel.book'),
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='admin_panel.chapter'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='admin_panel.topic'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='admin_panel.lessonplanrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('academic_year', 'class_fk', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectperiod',
            unique_together={('group', 'subject', 'day')},
        ),
    ]
