# Generated by Django 5.2.3 on 2025-11-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_userrole'),
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_teacher', to='teacher_dashboard.teacher')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.createperiod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teacher', to='teacher_dashboard.teacher')),
            ],
        ),
    ]
