# Generated by Django 5.2.3 on 2025-11-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_teacherfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfixture',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
        ),
    ]
