# Generated by Django 5.2.3 on 2025-11-17 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_teacherfixture_subject'),
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherfixture',
            name='reason',
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherfixture',
            name='absent_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_fixtures', to='teacher_dashboard.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherfixture',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.subject'),
        ),
        migrations.AlterField(
            model_name='teacherfixture',
            name='substitute_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_fixtures', to='teacher_dashboard.teacher'),
        ),
    ]
