# Generated by Django 5.0.3 on 2025-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_teacherfixture_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
