# Generated by Django 5.0.3 on 2025-12-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_admission_father_email_admission_father_occupation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonday',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='end_page',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='number',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='start_page',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='rescheduled_date',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='lessonplanrequest',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='lessonplanrequest',
            name='section',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='book',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='ai_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='day_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='no_of_periods',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='planning_style',
            field=models.CharField(default='ai', max_length=50),
        ),
    ]
