# Generated by Django 5.0.3 on 2025-12-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='admin_panel.subtopic'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='admin_panel.topic'),
        ),
    ]
