# Generated by Django 5.0.3 on 2025-12-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_book_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='class_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='chapters/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject'),
            preserve_default=False,
        ),
    ]
