# Generated by Django 5.0.3 on 2025-12-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_chapter_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonday',
            old_name='activities',
            new_name='assessment_tasks',
        ),
        migrations.RenameField(
            model_name='lessonday',
            old_name='assessment',
            new_name='homework_tasks',
        ),
        migrations.RenameField(
            model_name='lessonday',
            old_name='homework',
            new_name='practice_work',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='ai_source',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='worksheet',
        ),
        migrations.RemoveField(
            model_name='lessonplanrequest',
            name='chapter_title',
        ),
        migrations.RemoveField(
            model_name='lessonplanrequest',
            name='no_of_periods',
        ),
        migrations.RemoveField(
            model_name='lessonplanrequest',
            name='topic_title',
        ),
        migrations.AddField(
            model_name='lessonday',
            name='learning_objectives',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonday',
            name='teaching_content',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplanrequest',
            name='chapter',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplanrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonplanrequest',
            name='total_periods',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='day_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.lessonplanrequest'),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='planning_style',
            field=models.CharField(choices=[('rule_based', 'Rule Based'), ('ai', 'AI Generated')], default='rule_based', max_length=20),
        ),
    ]
