# Generated by Django 5.0.3 on 2025-12-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_rename_activities_lessonday_assessment_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplanrequest',
            name='topics',
            field=models.ManyToManyField(to='admin_panel.topic'),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='planning_style',
            field=models.CharField(default='rule-based', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonplanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated')], default='pending', max_length=20),
        ),
    ]
