# Generated by Django 5.0.3 on 2025-12-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_lessonplanrequest_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='admin_panel.lessonplanrequest'),
        ),
    ]
