# Generated by Django 5.0.3 on 2025-12-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_leavetype_leaveapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_all_employee', 'Can view all employees')]},
        ),
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'permissions': [('view_all_leaveapplication', 'Can view all leave applications')]},
        ),
    ]
