# Generated by Django 5.0.8 on 2026-01-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_jobtype_staffcategory_leavetype_yearly_quota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='yearly_quota',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='allowed_leave_types',
            field=models.ManyToManyField(blank=True, related_name='job_types', to='admin_panel.leavetype'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
