# Generated by Django 5.0.8 on 2026-01-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_remove_leavetype_yearly_quota_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='max_days_per_year',
            new_name='yearly_quota',
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
