# Generated by Django 5.0.8 on 2026-01-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_rename_max_days_per_year_leavetype_yearly_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
