# Generated by Django 5.0.8 on 2026-01-13 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_employee_is_teacher'),
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Grade Policy', max_length=120)),
                ('a_min', models.FloatField(default=80)),
                ('b_min', models.FloatField(default=70)),
                ('c_min', models.FloatField(default=60)),
                ('d_min', models.FloatField(default=50)),
                ('e_min', models.FloatField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='MLModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='RandomForest', max_length=50)),
                ('model_path', models.CharField(max_length=255)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_templates', to='admin_panel.appraisalcycle')),
                ('grade_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.gradepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='KpiRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('kpi_key', models.CharField(choices=[('pass_rate', 'Pass Rate (%)'), ('ab_rate', 'A+B Rate (%)'), ('a_rate', 'A Rate (%)'), ('results_count', 'Results Count'), ('classes_taught', 'Classes Taught (unique class-section-subject)'), ('fixtures_substitute', 'Substitute Fixtures Count'), ('fixtures_absent', 'Absent Fixtures Count'), ('workshops_attended', 'Workshops Attended'), ('trainings_given', 'Trainings Given'), ('extra_curricular', 'Extra Curricular Activities')], max_length=50)),
                ('weight', models.FloatField(default=10)),
                ('target_value', models.FloatField(default=0)),
                ('scoring_method', models.CharField(choices=[('linear', 'Linear (actual/target)'), ('threshold', 'Threshold (bands)')], default='linear', max_length=20)),
                ('thresholds', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='admin_panel.kpitemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAppraisalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_metrics', models.JSONField(blank=True, default=dict)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('achievements', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('improvement_plan', models.TextField(blank=True)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('final_band', models.CharField(blank=True, choices=[('Outstanding', 'Outstanding'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Average', 'Average'), ('Below Average', 'Below Average')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.appraisalcycle')),
                ('kpi_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.kpitemplate')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='TeacherActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('EXTRA', 'Extra Curricular'), ('WORKSHOP_ATTEND', 'Workshop Attended'), ('TRAINING_GIVEN', 'Training Given')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='admin_panel.teacherappraisalsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('band', models.CharField(default='Pending', max_length=30)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('predicted_band', models.CharField(blank=True, max_length=30)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='admin_panel.teacherappraisalsubmission')),
            ],
        ),
    ]
