# Generated by Django 5.0.8 on 2026-01-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_appraisalcycle_gradepolicy_mlmodelartifact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheractivity',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_activities', to='admin_panel.teacherappraisalsubmission'),
        ),
    ]
