# Generated by Django 5.0.8 on 2026-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_alter_teacheractivity_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherappraisalsubmission',
            name='manual_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='kpirule',
            name='kpi_key',
            field=models.CharField(choices=[('pass_rate', 'Pass Rate (%)'), ('ab_rate', 'A+B Rate (%)'), ('a_rate', 'A Rate (%)'), ('results_count', 'Results Count'), ('classes_taught', 'Classes Taught (unique class-section-subject)'), ('fixtures_substitute', 'Substitute Fixtures Count'), ('fixtures_absent', 'Absent Fixtures Count'), ('workshops_attended', 'Workshops Attended'), ('trainings_given', 'Trainings Given'), ('extra_curricular', 'Extra Curricular Activities'), ('diary_submissions', 'Diary Submission Regularity'), ('lesson_plans_created', 'Lesson Plan Completion'), ('lesson_days_created', 'Lesson Days Generated'), ('lecture_notes_uploaded', 'Lecture Notes Upload'), ('assignments_uploaded', 'Assignments Uploaded'), ('quizzes_created', 'Quizzes Created'), ('manual_custom', 'Custom KPI (Manual Rating 0-10)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kpirule',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
