# Generated by Django 5.0.8 on 2026-01-23 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_teacherappraisalsubmission_manual_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpirule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpirule',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpirule',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='mlmodelartifact',
            name='feature_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='kpirule',
            name='kpi_key',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='kpirule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='kpirule',
            unique_together={('template', 'kpi_key')},
        ),
    ]
