# Generated by Django 5.0.8 on 2026-01-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_kpirule_created_at_kpirule_is_manual_kpirule_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheractivity',
            name='entry_kind',
            field=models.CharField(choices=[('ACTIVITY', 'Activity / Training / Workshop'), ('MANUAL_KPI', 'Manual KPI (Auto Rated)')], default='ACTIVITY', max_length=20),
        ),
        migrations.AddField(
            model_name='teacheractivity',
            name='manual_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_evidences', to='admin_panel.kpirule'),
        ),
        migrations.AddField(
            model_name='teacheractivity',
            name='system_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacheractivity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('EXTRA', 'Extra Curricular'), ('WORKSHOP_ATTEND', 'Workshop Attended'), ('TRAINING_GIVEN', 'Training Given')], default='', max_length=30),
        ),
    ]
