# Generated by Django 5.0.8 on 2026-01-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_academiccalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendarevent',
            name='responsibility',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='academiccalendarevent',
            name='streams',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='event_type',
            field=models.CharField(choices=[('gazetted', 'Gazetted Holidays'), ('college_assess', 'College Assess/Admin'), ('college_event', 'College Events'), ('mat_camb_assess', 'Mat/Camb Assess'), ('pre_primary', 'Pre-Primary'), ('speaker_train', 'Speaker/Ses/Train'), ('eca_cca', 'ECA/CCA'), ('ptm', 'PTM'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='academiccalendarevent',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
