# Generated by Django 5.2.3 on 2026-05-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_academiccalendarevent_responsibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonday',
            options={'ordering': ['day_number']},
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='admin_panel.lessonplanrequest'),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='teaching_content',
            field=models.TextField(blank=True),
        ),
    ]
