# Generated by Django 6.0.6 on 2026-07-14 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_automationjob_feegenerationlog_feegenerationsettings_and_more'),
        ('teacher_dashboard', '0002_attendance_marked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfixture',
            name='automation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='automation_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('notification_failed', 'Notification Failed')], default='assigned', max_length=30),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='fixture_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto_absence', 'Auto Absence'), ('auto_leave', 'Auto Leave')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('leave', 'Leave')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_absences', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_absences', to='admin_panel.leaveapplication')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_absences', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['-absence_date', '-created_at'],
                'unique_together': {('teacher', 'absence_date', 'source', 'leave_application')},
            },
        ),
        migrations.CreateModel(
            name='TeacherFixtureNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In App')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='admin_panel.teacherfixture')),
                ('recipient_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_notification_logs', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('fixture_assigned', 'Fixture Assigned'), ('absence_covered', 'Absence Covered'), ('fixture_unassigned', 'Fixture Unassigned')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_notifications', to='admin_panel.teacherfixture')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_notifications', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAbsenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('skipped', 'Skipped')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admin_panel.teacherabsence')),
                ('assigned_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.assignedperiod')),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_results', to='admin_panel.teacherfixture')),
            ],
            options={
                'ordering': ['assigned_period__period__start_time', 'id'],
                'unique_together': {('absence', 'assigned_period')},
            },
        ),
    ]
