# Generated by Django 6.0.6 on 2026-07-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_teacherfixture_automation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfixturenotificationlog',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='admin_panel.teacherfixture'),
        ),
    ]
