# Generated by Django 6.0.6 on 2026-07-14 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_alter_teacherfixturenotificationlog_fixture'),
        ('teacher_dashboard', '0002_attendance_marked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherabsence',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherabsence',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherabsenceresult',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherabsenceresult',
            name='selection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherabsenceresult',
            name='selection_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='assigned_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='admin_panel.assignedperiod'),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='assignment_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('overridden', 'Overridden')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='fixture_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('uncovered', 'Uncovered')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='original_substitute_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_substitute_fixtures', to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_teacher_fixtures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='response_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='response_status',
            field=models.CharField(choices=[('final', 'Final'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='final', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='selection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='selection_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherabsence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherabsenceresult',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherfixturenotificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In App'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherfixturenotificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.CreateModel(
            name='SubjectSubstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('class_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.class')),
                ('eligible_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_targets', to='admin_panel.subject')),
                ('source_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_sources', to='admin_panel.subject')),
            ],
            options={
                'ordering': ['source_subject__name', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('meeting', 'Meeting'), ('training', 'Training'), ('exam_duty', 'Exam Duty'), ('leave', 'Leave'), ('manual_block', 'Manual Block')], default='unavailable', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.createperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['-date', 'teacher__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFixtureCandidateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('selected', 'Selected'), ('eligible', 'Eligible'), ('excluded', 'Excluded')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_logs', to='admin_panel.teacherabsence')),
                ('absence_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_logs', to='admin_panel.teacherabsenceresult')),
                ('assigned_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_logs', to='admin_panel.assignedperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_candidate_logs', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['-score', 'teacher__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFixtureHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='fixture_handovers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='admin_panel.teacherfixture')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_fixture_handovers', to='teacher_dashboard.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTeachingEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_group', models.CharField(blank=True, default='', max_length=100)),
                ('campus', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('class_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_eligibilities', to='teacher_dashboard.teacher')),
            ],
            options={
                'ordering': ['teacher__name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Timetable', max_length=120)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.academicyear')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignedperiod',
            name='timetable_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_periods', to='admin_panel.timetableversion'),
        ),
        migrations.AddField(
            model_name='teacherfixture',
            name='timetable_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='admin_panel.timetableversion'),
        ),
        migrations.AddConstraint(
            model_name='teacherfixture',
            constraint=models.UniqueConstraint(fields=('fixture_date', 'assigned_period'), name='uniq_fixture_date_assigned_period'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectsubstitutionrule',
            unique_together={('source_subject', 'eligible_subject', 'class_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherteachingeligibility',
            unique_together={('teacher', 'subject', 'class_fk', 'faculty_group', 'campus')},
        ),
    ]
