# Generated by Django 6.0.6 on 2026-07-21 09:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_procurementcategory_vehicle_vendor_inventoryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('scheduled_departure', models.TimeField()),
                ('actual_departure', models.TimeField(blank=True, null=True)),
                ('students_transported', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_time', 'On Time'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='admin_panel.transportroute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='admin_panel.vehicle')),
            ],
            options={
                'ordering': ['-service_date', 'scheduled_departure'],
            },
        ),
    ]
