# Generated by Django 4.2.16 on 2026-07-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_purchaserequest_received_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('timing', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='admin_panel.teacher')),
            ],
            options={
                'ordering': ['date', 'timing'],
            },
        ),
    ]
