# Generated by Django 4.2.16 on 2026-07-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0003_teacher_employee'),
        ('admin_panel', '0041_teacherduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherduty',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='teacher_dashboard.teacher'),
        ),
    ]
