# Generated by Django 4.2.16 on 2026-07-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_appraisalsection_kpirule_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_letter',
            field=models.FileField(blank=True, null=True, upload_to='employees/appointment/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnic_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/cnic/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='admin_panel.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employees/resume/'),
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Certificate', max_length=150)),
                ('file', models.FileField(upload_to='employees/certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admin_panel.employee')),
            ],
        ),
    ]
