# Generated by Django 6.0.6 on 2026-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_merge_20260810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiondocument',
            name='document_type',
            field=models.CharField(choices=[('STUDENT_PHOTO', 'Student Photograph'), ('B_FORM', 'B-Form'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('GUARDIAN_CNIC', 'Guardian CNIC'), ('PREVIOUS_REPORT', 'Previous School Report'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
