# Generated by Django 6.0.6 on 2026-09-07 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0048_bulkstudentcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_purchaserequest', 'Can approve a purchase request')]},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
