# Generated by Django 4.2.16 on 2026-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_initial'),
        ('parent_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', to='student_profile.student'),
        ),
    ]
