# Generated by Django 5.2 on 2026-05-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0031_academiccalendarevent_responsibility_and_more"),
        ("student_profile", "0002_initial"),
        ("teacher_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scanned_file",
                    models.FileField(blank=True, null=True, upload_to="answer_sheets/"),
                ),
                ("is_submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CentralizedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.PositiveIntegerField()),
                ("obtained_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("F", "F"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_pass", models.BooleanField(default=False)),
                ("class_position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "section_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("remarks", models.TextField(blank=True)),
                ("compiled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="exam_system.answersheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly Test"),
                            ("MIDTERM", "Mid Term"),
                            ("FINAL", "Final Term"),
                            ("WEEKLY", "Weekly Test"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.academicyear",
                    ),
                ),
                (
                    "class_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=50)),
                (
                    "exam_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="exam_system.examplan",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam_plan", "subject")},
            },
        ),
        migrations.AddField(
            model_name="answersheet",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_system.examschedule",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_set",
                    models.CharField(
                        choices=[
                            ("A", "Set A"),
                            ("B", "Set B"),
                            ("C", "Set C"),
                            ("SINGLE", "Single Paper"),
                        ],
                        default="SINGLE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked & Ready"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("unlock_time", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="exam_papers/"),
                ),
                ("watermark_text", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.section",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answersheet",
            name="paper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_system.generatedpaper",
            ),
        ),
        migrations.CreateModel(
            name="InvigilatorDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(blank=True, max_length=50)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invigilator_duties",
                        to="exam_system.examschedule",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_dashboard.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "Viewed"),
                            ("DOWNLOAD", "Downloaded"),
                            ("PRINT", "Printed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_system.generatedpaper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.PositiveIntegerField(default=100)),
                ("passing_marks", models.PositiveIntegerField(default=40)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="exam_system.examplan",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generatedpaper",
            name="blueprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="exam_system.paperblueprint",
            ),
        ),
        migrations.CreateModel(
            name="BlueprintRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("SHORT", "Short Question"),
                            ("LONG", "Long Question"),
                            ("CONCEPTUAL", "Conceptual"),
                            ("CASE_BASED", "Case Based"),
                            ("PRACTICAL", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("marks_each", models.PositiveIntegerField()),
                ("easy_percent", models.PositiveIntegerField(default=30)),
                ("medium_percent", models.PositiveIntegerField(default=50)),
                ("hard_percent", models.PositiveIntegerField(default=20)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="exam_system.paperblueprint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("SHORT", "Short Question"),
                            ("LONG", "Long Question"),
                            ("CONCEPTUAL", "Conceptual"),
                            ("CASE_BASED", "Case Based"),
                            ("PRACTICAL", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("marks", models.PositiveIntegerField(default=1)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("REMEMBER", "Remember"),
                            ("UNDERSTAND", "Understand"),
                            ("APPLY", "Apply"),
                            ("ANALYZE", "Analyze"),
                            ("EVALUATE", "Evaluate"),
                            ("CREATE", "Create"),
                        ],
                        default="UNDERSTAND",
                        max_length=20,
                    ),
                ),
                ("topic_tag", models.CharField(blank=True, max_length=100)),
                ("option_a", models.CharField(blank=True, max_length=255, null=True)),
                ("option_b", models.CharField(blank=True, max_length=255, null=True)),
                ("option_c", models.CharField(blank=True, max_length=255, null=True)),
                ("option_d", models.CharField(blank=True, max_length=255, null=True)),
                ("correct_answer", models.TextField(blank=True)),
                ("ai_generated", models.BooleanField(default=False)),
                ("human_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generatedpaper",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="papers", to="exam_system.question"
            ),
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.academicyear",
                    ),
                ),
                (
                    "class_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="admin_panel.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("subject", "class_fk", "academic_year")},
            },
        ),
        migrations.AddField(
            model_name="question",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exam_system.questionbank",
            ),
        ),
        migrations.CreateModel(
            name="QuestionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True)),
                (
                    "teacher_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("teacher_remarks", models.TextField(blank=True)),
                (
                    "answer_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exam_system.answersheet",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_system.question",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                        ],
                        default="ABSENT",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teacher_dashboard.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile.student",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_system.examschedule",
                    ),
                ),
            ],
            options={
                "unique_together": {("schedule", "student")},
            },
        ),
        migrations.CreateModel(
            name="ExamSeatingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=20)),
                ("room", models.CharField(blank=True, max_length=50)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_plans",
                        to="exam_system.examschedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("schedule", "student")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="answersheet",
            unique_together={("schedule", "student")},
        ),
        migrations.CreateModel(
            name="PaperApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Subject Teacher"),
                            ("COORDINATOR", "Subject Coordinator"),
                            ("ACADEMIC_HEAD", "Academic Head"),
                            ("CONTROLLER", "Exam Controller"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="exam_system.generatedpaper",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("paper", "stage")},
            },
        ),
    ]
