# Generated by Django 4.2.16 on 2026-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapproval',
            name='stage',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('COORDINATOR', 'Subject Coordinator'), ('ACADEMIC_HEAD', 'HOD / Academic Head'), ('CONTROLLER', 'Examination Controller')], max_length=20),
        ),
    ]
