# Generated by Django 5.2 on 2026-08-16 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0002_alter_paperapproval_stage'),
        ('student_profile', '0003_student_admission_profile_fields'),
        ('teacher_dashboard', '0003_teacher_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpaper',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperapproval',
            name='stage',
            field=models.CharField(choices=[('TEACHER', 'Subject Teacher'), ('COORDINATOR', 'Subject Coordinator'), ('ACADEMIC_HEAD', 'HOD / Academic Head'), ('CONTROLLER', 'Examination Controller')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ExamIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('CHEATING', 'Cheating / Unfair Means'), ('ABSENT', 'Mass Absence'), ('PAPER_LEAK', 'Paper Leak Suspicion'), ('DISRUPTION', 'Disruption in Hall'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_dashboard.teacher')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='exam_system.examschedule')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_profile.student')),
            ],
        ),
    ]
