# Generated by Django 5.2 on 2026-08-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0003_generatedpaper_final_approved_at_and_more'),
        ('admin_panel', '0031_academiccalendarevent_responsibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralizedresult',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=3),
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='admin_panel.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='exam_system.gradingscale')),
            ],
            options={
                'ordering': ['-min_percent'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weightage_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('exam_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='exam_system.examplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='admin_panel.subject')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('exam_plan', 'subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TermWeightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_weightages', to='admin_panel.academicyear')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_weightages', to='admin_panel.class')),
                ('exam_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_weightage', to='exam_system.examplan')),
            ],
            options={
                'ordering': ['exam_plan__start_date'],
                'unique_together': {('class_fk', 'academic_year', 'exam_plan')},
            },
        ),
    ]
