# Generated by Django 6.0.6 on 2026-07-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0015_feevoucher_year_alter_feevoucher_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationqueue',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.teacher'),
        ),
        migrations.AlterField(
            model_name='notificationqueue',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.student'),
        ),
    ]
