# Generated by Django 6.0.6 on 2026-07-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0016_notificationqueue_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
