# Generated by Django 6.0.6 on 2026-07-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0017_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=20)),
                ('period_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_fixtures', to='edupilot_core.teacher')),
                ('replacement_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_fixtures', to='edupilot_core.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.period')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPeriods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.period')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edupilot_core.period')),
            ],
        ),
    ]
