# Generated by Django 6.0.6 on 2026-07-27 06:54

import django.db.models.deletion
from django.db import migrations, models


def _normalized(value):
    return ' '.join((value or '').strip().casefold().split())


def _unique_candidate(candidates, claimed):
    available = [candidate for candidate in candidates if candidate.pk not in claimed]
    return available[0] if len(available) == 1 else None, len(available)


def map_canonical_records(apps, schema_editor):
    LegacyStudent = apps.get_model('edupilot_core', 'Student')
    PortalStudent = apps.get_model('student_profile', 'Student')
    LegacyTeacher = apps.get_model('edupilot_core', 'Teacher')
    PortalTeacher = apps.get_model('teacher_dashboard', 'Teacher')
    Audit = apps.get_model('edupilot_core', 'CanonicalMappingAudit')

    claimed_students = set(
        LegacyStudent.objects.exclude(canonical_student_id=None)
        .values_list('canonical_student_id', flat=True)
    )
    portal_students = list(PortalStudent.objects.select_related('user').all())
    student_names = {}
    audit_rows = []
    for portal in portal_students:
        student_names.setdefault(_normalized(portal.name), []).append(portal)

    for legacy in LegacyStudent.objects.filter(canonical_student_id=None).iterator():
        candidate = None
        candidate_count = 0
        matched_by = ''
        identifiers = {
            _normalized(legacy.admission_number),
            _normalized(legacy.student_id),
        } - {''}

        if identifiers:
            identifier_matches = [
                portal for portal in portal_students
                if _normalized(portal.student_id) in identifiers
                or (
                    portal.user_id
                    and _normalized(portal.user.username) in identifiers
                )
            ]
            candidate, candidate_count = _unique_candidate(identifier_matches, claimed_students)
            matched_by = 'student_id'

        if candidate is None and candidate_count == 0:
            name_matches = student_names.get(_normalized(legacy.full_name), [])
            candidate, candidate_count = _unique_candidate(name_matches, claimed_students)
            matched_by = 'exact_name'

        if candidate:
            legacy.canonical_student_id = candidate.pk
            legacy.save(update_fields=['canonical_student'])
            claimed_students.add(candidate.pk)
            status = 'MATCHED'
            details = 'Legacy student linked to canonical portal student.'
            canonical_pk = candidate.pk
        else:
            status = 'AMBIGUOUS' if candidate_count > 1 else 'UNMATCHED'
            details = (
                'Multiple canonical candidates found; manual review required.'
                if candidate_count > 1
                else 'No safe canonical match found; legacy fallback retained.'
            )
            canonical_pk = None
            matched_by = ''

        audit_rows.append(Audit(
            entity_type='STUDENT',
            legacy_pk=legacy.pk,
            canonical_pk=canonical_pk,
            status=status,
            matched_by=matched_by,
            details=details,
        ))

    claimed_teachers = set(
        LegacyTeacher.objects.exclude(canonical_teacher_id=None)
        .values_list('canonical_teacher_id', flat=True)
    )
    portal_teachers = list(PortalTeacher.objects.select_related('user', 'employee').all())
    teacher_names = {}
    for portal in portal_teachers:
        teacher_names.setdefault(_normalized(portal.name), []).append(portal)

    for legacy in LegacyTeacher.objects.filter(canonical_teacher_id=None).iterator():
        candidate = None
        candidate_count = 0
        matched_by = ''

        if legacy.teacher_id:
            id_matches = [
                portal for portal in portal_teachers
                if portal.user_id
                and _normalized(portal.user.username) == _normalized(legacy.teacher_id)
            ]
            candidate, candidate_count = _unique_candidate(id_matches, claimed_teachers)
            matched_by = 'user_account'

        if candidate is None and candidate_count == 0 and legacy.email:
            email_matches = [
                portal for portal in portal_teachers
                if _normalized(portal.email) == _normalized(legacy.email)
                or (
                    portal.employee_id
                    and _normalized(portal.employee.email) == _normalized(legacy.email)
                )
            ]
            candidate, candidate_count = _unique_candidate(email_matches, claimed_teachers)
            matched_by = 'email'

        if candidate is None and candidate_count == 0 and legacy.phone:
            phone_matches = [
                portal for portal in portal_teachers
                if _normalized(str(portal.phone or '')) == _normalized(legacy.phone)
                or (
                    portal.employee_id
                    and _normalized(portal.employee.phone) == _normalized(legacy.phone)
                )
            ]
            candidate, candidate_count = _unique_candidate(phone_matches, claimed_teachers)
            matched_by = 'phone'

        if candidate is None and candidate_count == 0:
            name_matches = teacher_names.get(_normalized(legacy.name), [])
            candidate, candidate_count = _unique_candidate(name_matches, claimed_teachers)
            matched_by = 'exact_name'

        if candidate:
            legacy.canonical_teacher_id = candidate.pk
            legacy.save(update_fields=['canonical_teacher'])
            claimed_teachers.add(candidate.pk)
            status = 'MATCHED'
            details = 'Legacy teacher linked to canonical portal teacher.'
            canonical_pk = candidate.pk
        else:
            status = 'AMBIGUOUS' if candidate_count > 1 else 'UNMATCHED'
            details = (
                'Multiple canonical candidates found; manual review required.'
                if candidate_count > 1
                else 'No safe canonical match found; legacy fallback retained.'
            )
            canonical_pk = None
            matched_by = ''

        audit_rows.append(Audit(
            entity_type='TEACHER',
            legacy_pk=legacy.pk,
            canonical_pk=canonical_pk,
            status=status,
            matched_by=matched_by,
            details=details,
        ))

    Audit.objects.bulk_create(audit_rows, batch_size=1000)

    student_models = (
        apps.get_model('edupilot_core', 'StudentFeeAssignment'),
        apps.get_model('edupilot_core', 'StudentLedger'),
        apps.get_model('edupilot_core', 'StudentBalance'),
        apps.get_model('edupilot_core', 'FeeVoucher'),
        apps.get_model('edupilot_core', 'AutomationJobDetail'),
    )
    for model in student_models:
        for record in model.objects.filter(
            canonical_student_id=None,
            student__canonical_student_id__isnull=False,
        ).iterator():
            record.canonical_student_id = record.student.canonical_student_id
            record.save(update_fields=['canonical_student'])

    NotificationQueue = apps.get_model('edupilot_core', 'NotificationQueue')
    for record in NotificationQueue.objects.filter(
        canonical_student_id=None,
        student__canonical_student_id__isnull=False,
    ).iterator():
        record.canonical_student_id = record.student.canonical_student_id
        record.save(update_fields=['canonical_student'])
    for record in NotificationQueue.objects.filter(
        canonical_teacher_id=None,
        teacher__canonical_teacher_id__isnull=False,
    ).iterator():
        record.canonical_teacher_id = record.teacher.canonical_teacher_id
        record.save(update_fields=['canonical_teacher'])

    teacher_models = (
        apps.get_model('edupilot_core', 'SalaryStructure'),
        apps.get_model('edupilot_core', 'SalaryVoucher'),
        apps.get_model('edupilot_core', 'SalaryAutomationJobDetail'),
    )
    for model in teacher_models:
        for record in model.objects.filter(
            canonical_teacher_id=None,
            teacher__canonical_teacher_id__isnull=False,
        ).iterator():
            record.canonical_teacher_id = record.teacher.canonical_teacher_id
            record.save(update_fields=['canonical_teacher'])


def clear_canonical_mappings(apps, schema_editor):
    apps.get_model('edupilot_core', 'CanonicalMappingAudit').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('edupilot_core', '0018_period_fixture_assignedperiods_absence'),
        ('student_profile', '0002_initial'),
        ('teacher_dashboard', '0003_teacher_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjobdetail',
            name='canonical_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_job_details', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='canonical_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_fee_vouchers', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='canonical_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_notifications', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='notificationqueue',
            name='canonical_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_notifications', to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='salaryautomationjobdetail',
            name='canonical_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_salary_job_details', to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='canonical_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_salary_structure', to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='salaryvoucher',
            name='canonical_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_salary_vouchers', to='teacher_dashboard.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='canonical_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_legacy_record', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='studentbalance',
            name='canonical_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_balance', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='canonical_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_fee_assignment', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='studentledger',
            name='canonical_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_ledger_entries', to='student_profile.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='canonical_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_legacy_record', to='teacher_dashboard.teacher'),
        ),
        migrations.CreateModel(
            name='CanonicalMappingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10)),
                ('legacy_pk', models.PositiveBigIntegerField()),
                ('canonical_pk', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('AMBIGUOUS', 'Ambiguous'), ('UNMATCHED', 'Unmatched'), ('INVALID', 'Invalid')], max_length=12)),
                ('matched_by', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'legacy_pk'), name='unique_canonical_mapping_audit')],
            },
        ),
        migrations.RunPython(map_canonical_records, clear_canonical_mappings),
    ]
