# Generated by Django 6.0.6 on 2026-07-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_purchaserequest_received_on'),
        ('edupilot_core', '0020_sync_existing_canonical_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('EVENT', 'Event'), ('HOLIDAY', 'Holiday'), ('ALERT', 'Alert / Warning'), ('NOTICE', 'Administrative Notice'), ('MAINTENANCE', 'System Maintenance')], default='NOTICE', max_length=20)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('TEACHERS', 'Teachers Only'), ('PARENTS', 'Parents Only'), ('ADMINS', 'Administrators Only'), ('CLASS', 'Specific Class')], default='ALL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('publish_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('total_intended_recipients', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='admin_panel.class')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push')], default='IN_APP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='edupilot_core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='edupilot_core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-publish_date'], name='edupilot_co_status_99ce06_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['audience', 'status'], name='edupilot_co_audienc_3df95b_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['category'], name='edupilot_co_categor_981612_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementnotification',
            index=models.Index(fields=['announcement', 'user'], name='edupilot_co_announc_d548cc_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementnotification',
            index=models.Index(fields=['status'], name='edupilot_co_status_ac9d9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementnotification',
            constraint=models.UniqueConstraint(fields=('announcement', 'user', 'notification_type'), name='unique_announcement_notification'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement', 'user'], name='edupilot_co_announc_df9a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['read_at'], name='edupilot_co_read_at_71e5e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read'),
        ),
    ]
