# Generated by Django 6.0.6 on 2026-08-03 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_voucher_deliveries(apps, schema_editor):
    FeeVoucher = apps.get_model('edupilot_core', 'FeeVoucher')
    LegacyStudent = apps.get_model('edupilot_core', 'Student')
    VoucherDelivery = apps.get_model('edupilot_core', 'VoucherDelivery')
    PortalNotification = apps.get_model('edupilot_core', 'PortalNotification')
    Student = apps.get_model('student_profile', 'Student')
    Parent = apps.get_model('parent_dashboard', 'Parent')
    ClassTeacher = apps.get_model('admin_panel', 'ClassTeacher')

    students = {
        row['id']: row
        for row in Student.objects.values(
            'id', 'user_id', 'name', 'student_id', 'class_fk_id',
            'section_id', 'academic_year_id'
        )
    }
    legacy_students = dict(
        LegacyStudent.objects.exclude(canonical_student_id=None).values_list(
            'id', 'canonical_student_id'
        )
    )
    parent_users = dict(
        Parent.objects.exclude(user_id=None).values_list('id', 'user_id')
    )
    parents_by_student = {}
    for parent_id, student_id in Parent.students.through.objects.values_list(
        'parent_id', 'student_id'
    ):
        user_id = parent_users.get(parent_id)
        if user_id:
            parents_by_student.setdefault(student_id, set()).add(user_id)

    teachers_by_class = {}
    for class_id, section_id, year_id, user_id in ClassTeacher.objects.exclude(
        teacher__user_id=None
    ).values_list('class_fk_id', 'section_id', 'academic_year_id', 'teacher__user_id'):
        teachers_by_class.setdefault((class_id, section_id, year_id), set()).add(user_id)

    deliveries = []
    notifications = []
    for voucher in FeeVoucher.objects.all().iterator(chunk_size=500):
        student_id = voucher.canonical_student_id or legacy_students.get(voucher.student_id)
        student = students.get(student_id)
        if not student:
            continue
        recipients = {}
        if student['user_id']:
            recipients[student['user_id']] = 'STUDENT'
        for user_id in parents_by_student.get(student_id, ()):
            recipients[user_id] = 'PARENT'
        teacher_key = (
            student['class_fk_id'], student['section_id'], student['academic_year_id']
        )
        for user_id in teachers_by_class.get(teacher_key, ()):
            recipients[user_id] = 'TEACHER'

        for user_id, role in recipients.items():
            deliveries.append(VoucherDelivery(
                voucher_id=voucher.pk,
                recipient_id=user_id,
                related_student_id=student_id,
                recipient_role=role,
            ))
            notifications.append(PortalNotification(
                recipient_id=user_id,
                notification_type='VOUCHER',
                title=f"Fee voucher available - {student['name']}",
                message=(
                    f'{voucher.month} {voucher.year} fee voucher for {student["name"]} '
                    f'is ready. Amount: PKR {voucher.net_amount}.'
                ),
                related_student_id=student_id,
                voucher_id=voucher.pk,
            ))
        if len(deliveries) >= 1000:
            VoucherDelivery.objects.bulk_create(deliveries, ignore_conflicts=True)
            PortalNotification.objects.bulk_create(notifications, ignore_conflicts=True)
            deliveries.clear()
            notifications.clear()

    if deliveries:
        VoucherDelivery.objects.bulk_create(deliveries, ignore_conflicts=True)
        PortalNotification.objects.bulk_create(notifications, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_dutyevent_teacherduty_event'),
        ('edupilot_core', '0022_automation_progress_tracking'),
        ('parent_dashboard', '0003_alter_parent_phone_alter_parent_students'),
        ('student_profile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('VOUCHER', 'Fee voucher'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to='student_profile.student')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='edupilot_core.feevoucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='portal_notify_recipient_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'voucher', 'notification_type'), name='unique_voucher_portal_notification')],
            },
        ),
        migrations.CreateModel(
            name='VoucherDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('STUDENT', 'Student'), ('PARENT', 'Parent'), ('TEACHER', 'Teacher')], max_length=10)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_deliveries', to=settings.AUTH_USER_MODEL)),
                ('related_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_deliveries', to='student_profile.student')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='edupilot_core.feevoucher')),
            ],
            options={
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['recipient', '-delivered_at'], name='voucher_rec_delivered_idx'), models.Index(fields=['recipient', 'dismissed_at'], name='voucher_rec_dismissed_idx')],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'recipient'), name='unique_voucher_recipient_delivery')],
            },
        ),
        migrations.RunPython(backfill_voucher_deliveries, migrations.RunPython.noop),
    ]
