# Generated by Django 6.0.6 on 2026-09-08 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0003_mfadevice'),
        ('student_profile', '0003_student_admission_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('clinic', 'Clinic'), ('counselling', 'Counselling'), ('safeguarding', 'Safeguarding')], max_length=20)),
                ('consent_reference', models.CharField(max_length=255)),
                ('encrypted_notes', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_health_cases', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_profile.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('laboratory', models.CharField(max_length=100)),
                ('inventory_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('safety_notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='school_operations.labasset')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_lab_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('due_on', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=200)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='school_operations.librarybook')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='access_control.campus')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_profile.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='labasset',
            constraint=models.UniqueConstraint(fields=('campus', 'inventory_code'), name='campus_lab_inventory_code'),
        ),
        migrations.AddConstraint(
            model_name='libraryloan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book', 'student'), name='one_open_loan_per_book_student'),
        ),
    ]
