# Generated by Django 6.0.6 on 2026-09-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
