# Generated by Django 5.2 on 2026-08-15 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0048_bulkstudentcredential'),
        ('student_profile', '0003_student_admission_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePredictorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Default Campus', max_length=255)),
                ('grading_scale', models.JSONField(default=dict, help_text="Grade boundaries — keep grade keys aligned with exam_system.CentralizedResult.GRADE_CHOICES (A+, A, B, C, D, F), e.g. {'A+': [90,100], 'A': [80,89], 'B': [70,79]}")),
                ('assessment_weightages', models.JSONField(default=dict, help_text='Weight (%) per assessment category, must sum to 100')),
                ('minimum_data_requirement', models.PositiveIntegerField(default=2, help_text='Minimum number of graded assessments before a prediction is shown')),
                ('risk_thresholds', models.JSONField(default=dict, help_text="Predicted-score cutoffs, e.g. {'low':70,'moderate':60,'high':50,'critical':0}")),
                ('confidence_thresholds', models.JSONField(default=dict, help_text="e.g. {'high':5, 'medium':3, 'low':0} -> min assessment count for each level")),
                ('prediction_refresh_frequency_hours', models.PositiveIntegerField(default=24)),
                ('parent_visibility', models.BooleanField(default=True)),
                ('student_visibility', models.BooleanField(default=True)),
                ('teacher_access', models.BooleanField(default=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('alert_min_change_points', models.PositiveIntegerField(default=5, help_text='Suppress alerts for changes smaller than this (spec section 16)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Predictor Configuration',
                'verbose_name_plural': 'Grade Predictor Configuration',
            },
        ),
        migrations.CreateModel(
            name='StudentGradePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.FloatField(help_text='Weighted score from graded assessments so far')),
                ('predicted_score', models.FloatField()),
                ('predicted_score_low', models.FloatField(help_text='Lower bound of prediction range')),
                ('predicted_score_high', models.FloatField(help_text='Upper bound of prediction range')),
                ('predicted_grade', models.CharField(max_length=5)),
                ('grade_probability', models.JSONField(default=dict)),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('confidence_pct', models.FloatField(default=0)),
                ('trend', models.CharField(choices=[('rapidly_improving', 'Rapidly Improving'), ('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('high_risk', 'High Risk')], default='stable', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('assessments_used', models.PositiveIntegerField(default=0)),
                ('explanation', models.JSONField(default=dict, help_text="Factor -> qualitative label, e.g. {'Assignments':'Strong','Attendance':'Good'}")),
                ('weak_topics', models.JSONField(default=list)),
                ('strong_topics', models.JSONField(default=list)),
                ('last_calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='admin_panel.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='student_profile.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_predictions', to='admin_panel.subject')),
            ],
            options={
                'ordering': ['student__id', 'subject__name'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Assessment 1', 'Midterm'", max_length=100)),
                ('score', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grade_predictor.studentgradeprediction')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('improved', 'Grade Prediction Improved'), ('risk', 'Performance Risk'), ('target_reached', 'Target Within Reach')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('old_grade', models.CharField(blank=True, max_length=5)),
                ('new_grade', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='grade_predictor.studentgradeprediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeRiskIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('action', models.CharField(help_text="e.g. 'Assign remedial Algebra class'", max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='grade_predictor.studentgradeprediction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
